export const mockMenuItems = [
  {
    id: 1,
    label: "Pedro",
    info: "Info",
    value: "pedro",
  },
  {
    id: 2,
    label: "Colm",
    info: "Info",
    value: "colm",
    disabled: true,
  },
  {
    id: 3,
    label: "Doctor",
    info: "Info",
    value: "doctor",
  },
  {
    id: 4,
    label: "Rose",
    info: "Info",
    value: "rose",
  },
  {
    id: 5,
    label: "Alice",
    info: "Info",
    value: "alice",
  },
  {
    id: 6,
    label: "Bob",
    info: "Info",
    value: "bob",
  },
  {
    id: 7,
    label: "Charlie",
    info: "Info",
    value: "charlie",
  },
  {
    id: 8,
    label: "David",
    info: "Info",
    value: "david",
  },
  {
    id: 9,
    label: "Eve",
    info: "Info",
    value: "eve",
  },
  {
    id: 10,
    label: "Frank",
    info: "Info",
    value: "frank",
  },
  {
    id: 11,
    label: "Grace",
    info: "Info",
    value: "grace",
  },
  {
    id: 12,
    label: "Helen",
    info: "Info",
    value: "helen",
  },
  {
    id: 13,
    label: "Isaac",
    info: "Info",
    value: "isaac",
  },
  {
    id: 14,
    label: "Jack",
    info: "Info",
    value: "jack",
  },
  {
    id: 15,
    label: "Katie",
    info: "Info",
    value: "katie",
  },
  // Add more menu items here
];

export const mockPeople = [
  {
    id: 1,
    name: "Waneta Sandiland",
    email: "wsandiland0@arstechnica.com",
    username: "wsandiland0",
  },
  {
    id: 2,
    name: "Reba Hoopper",
    email: "rhoopper1@huffingtonpost.com",
    username: "rhoopper1",
  },
  {
    id: 3,
    name: "Phillipe Iacoviello",
    email: "piacoviello2@ucoz.com",
    username: "piacoviello2",
  },
  {
    id: 4,
    name: "Kaitlin Argo",
    email: "kargo3@huffingtonpost.com",
    username: "kargo3",
  },
  {
    id: 5,
    name: "Kandy Corbishley",
    email: "kcorbishley4@hhs.gov",
    username: "kcorbishley4",
  },
  {
    id: 6,
    name: "Madel Baldetti",
    email: "mbaldetti5@epa.gov",
    username: "mbaldetti5",
  },
  {
    id: 7,
    name: "Maryjane Zamudio",
    email: "mzamudio6@howstuffworks.com",
    username: "mzamudio6",
  },
  {
    id: 8,
    name: "Ortensia Crouse",
    email: "ocrouse7@cdbaby.com",
    username: "ocrouse7",
  },
  {
    id: 9,
    name: "Cherie Vern",
    email: "cvern8@foxnews.com",
    username: "cvern8",
  },
  {
    id: 10,
    name: "Odessa Archbutt",
    email: "oarchbutt9@wikia.com",
    username: "oarchbutt9",
  },
  {
    id: 11,
    name: "Barny Edlington",
    email: "bedlingtona@goo.ne.jp",
    username: "bedlingtona",
  },
  {
    id: 12,
    name: "Constancia Lichtfoth",
    email: "clichtfothb@pbs.org",
    username: "clichtfothb",
  },
  {
    id: 13,
    name: "Faith Nockles",
    email: "fnocklesc@joomla.org",
    username: "fnocklesc",
  },
  {
    id: 14,
    name: "Nolan Shyres",
    email: "nshyresd@exblog.jp",
    username: "nshyresd",
  },
  {
    id: 15,
    name: "Mabel Meaton",
    email: "mmeatone@webeden.co.uk",
    username: "mmeatone",
  },
  {
    id: 16,
    name: "Amalle Mullin",
    email: "amullinf@salon.com",
    username: "amullinf",
  },
  {
    id: 17,
    name: "Tandie Waddie",
    email: "twaddieg@wunderground.com",
    username: "twaddieg",
  },
  {
    id: 18,
    name: "Nicko Conant",
    email: "nconanth@wix.com",
    username: "nconanth",
  },
  {
    id: 19,
    name: "Gibby Dahill",
    email: "gdahilli@craigslist.org",
    username: "gdahilli",
  },
  {
    id: 20,
    name: "Gabriela Coleson",
    email: "gcolesonj@unc.edu",
    username: "gcolesonj",
  },
  {
    id: 21,
    name: "Jessalin Crosen",
    email: "jcrosenk@utexas.edu",
    username: "jcrosenk",
  },
  {
    id: 22,
    name: "Pattie Leirmonth",
    email: "pleirmonthl@alibaba.com",
    username: "pleirmonthl",
  },
  {
    id: 23,
    name: "Lamar Hartwright",
    email: "lhartwrightm@friendfeed.com",
    username: "lhartwrightm",
  },
  {
    id: 24,
    name: "Daniella Pecha",
    email: "dpechan@netlog.com",
    username: "dpechan",
  },
  {
    id: 25,
    name: "Yvonne Huc",
    email: "yhuco@sohu.com",
    username: "yhuco",
  },
  {
    id: 26,
    name: "Ev Seward",
    email: "esewardp@facebook.com",
    username: "esewardp",
  },
  {
    id: 27,
    name: "Hewet Kerby",
    email: "hkerbyq@liveinternet.ru",
    username: "hkerbyq",
  },
  {
    id: 28,
    name: "Ivor Crutch",
    email: "icrutchr@psu.edu",
    username: "icrutchr",
  },
  {
    id: 29,
    name: "Malissia Doppler",
    email: "mdopplers@seattletimes.com",
    username: "mdopplers",
  },
  {
    id: 30,
    name: "Fielding Bramstom",
    email: "fbramstomt@surveymonkey.com",
    username: "fbramstomt",
  },
  {
    id: 31,
    name: "Wat Stanway",
    email: "wstanwayu@sciencedaily.com",
    username: "wstanwayu",
  },
  {
    id: 32,
    name: "Ali Nelles",
    email: "anellesv@harvard.edu",
    username: "anellesv",
  },
  {
    id: 33,
    name: "Byrle Parren",
    email: "bparrenw@usgs.gov",
    username: "bparrenw",
  },
  {
    id: 34,
    name: "Brier Cordle",
    email: "bcordlex@army.mil",
    username: "bcordlex",
  },
  {
    id: 35,
    name: "Nevsa Siccombe",
    email: "nsiccombey@g.co",
    username: "nsiccombey",
  },
  {
    id: 36,
    name: "Evered McCartan",
    email: "emccartanz@liveinternet.ru",
    username: "emccartanz",
  },
  {
    id: 37,
    name: "Retha Laidler",
    email: "rlaidler10@home.pl",
    username: "rlaidler10",
  },
  {
    id: 38,
    name: "Mel Winsper",
    email: "mwinsper11@usda.gov",
    username: "mwinsper11",
  },
  {
    id: 39,
    name: "Theodore Attwoul",
    email: "tattwoul12@chronoengine.com",
    username: "tattwoul12",
  },
  {
    id: 40,
    name: "Heath Bastiman",
    email: "hbastiman13@dropbox.com",
    username: "hbastiman13",
  },
  {
    id: 41,
    name: "Shelden Filppetti",
    email: "sfilppetti14@netvibes.com",
    username: "sfilppetti14",
  },
  {
    id: 42,
    name: "Jsandye Pluck",
    email: "jpluck15@google.co.jp",
    username: "jpluck15",
  },
  {
    id: 43,
    name: "Weider Gilbeart",
    email: "wgilbeart16@sourceforge.net",
    username: "wgilbeart16",
  },
  {
    id: 44,
    name: "Arvie Dimmer",
    email: "adimmer17@etsy.com",
    username: "adimmer17",
  },
  {
    id: 45,
    name: "Eadmund Guterson",
    email: "eguterson18@bbb.org",
    username: "eguterson18",
  },
  {
    id: 46,
    name: "Chadwick Thornewill",
    email: "cthornewill19@prweb.com",
    username: "cthornewill19",
  },
  {
    id: 47,
    name: "Wileen Megarrell",
    email: "wmegarrell1a@google.nl",
    username: "wmegarrell1a",
  },
  {
    id: 48,
    name: "Cornell Lendon",
    email: "clendon1b@blog.com",
    username: "clendon1b",
  },
  {
    id: 49,
    name: "Idaline Corryer",
    email: "icorryer1c@slate.com",
    username: "icorryer1c",
  },
  {
    id: 50,
    name: "Richmond Gandar",
    email: "rgandar1d@wikispaces.com",
    username: "rgandar1d",
  },
  {
    id: 51,
    name: "Jedediah Blackater",
    email: "jblackater1e@shinystat.com",
    username: "jblackater1e",
  },
  {
    id: 52,
    name: "Elli Geyton",
    email: "egeyton1f@feedburner.com",
    username: "egeyton1f",
  },
  {
    id: 53,
    name: "Peta Exroll",
    email: "pexroll1g@admin.ch",
    username: "pexroll1g",
  },
  {
    id: 54,
    name: "Demetris Facher",
    email: "dfacher1h@google.com",
    username: "dfacher1h",
  },
  {
    id: 55,
    name: "Lynnelle Roderigo",
    email: "lroderigo1i@spotify.com",
    username: "lroderigo1i",
  },
  {
    id: 56,
    name: "Burl Ebbins",
    email: "bebbins1j@techcrunch.com",
    username: "bebbins1j",
  },
  {
    id: 57,
    name: "Rosetta Simoni",
    email: "rsimoni1k@mail.ru",
    username: "rsimoni1k",
  },
  {
    id: 58,
    name: "Orlando Castana",
    email: "ocastana1l@nih.gov",
    username: "ocastana1l",
  },
  {
    id: 59,
    name: "Marleah Tessington",
    email: "mtessington1m@ucsd.edu",
    username: "mtessington1m",
  },
  {
    id: 60,
    name: "Neda Glanville",
    email: "nglanville1n@oaic.gov.au",
    username: "nglanville1n",
  },
  {
    id: 61,
    name: "Burnaby Annetts",
    email: "bannetts1o@topsy.com",
    username: "bannetts1o",
  },
  {
    id: 62,
    name: "Ruprecht Seabourne",
    email: "rseabourne1p@naver.com",
    username: "rseabourne1p",
  },
  {
    id: 63,
    name: "Tully Glendenning",
    email: "tglendenning1q@deviantart.com",
    username: "tglendenning1q",
  },
  {
    id: 64,
    name: "Filbert De Simoni",
    email: "fde1r@mac.com",
    username: "fde1r",
  },
  {
    id: 65,
    name: "Valentine Bathurst",
    email: "vbathurst1s@cnet.com",
    username: "vbathurst1s",
  },
  {
    id: 66,
    name: "Blancha Towner",
    email: "btowner1t@nymag.com",
    username: "btowner1t",
  },
  {
    id: 67,
    name: "Leah Blenkin",
    email: "lblenkin1u@cdc.gov",
    username: "lblenkin1u",
  },
  {
    id: 68,
    name: "Abraham Kaufman",
    email: "akaufman1v@yelp.com",
    username: "akaufman1v",
  },
  {
    id: 69,
    name: "Felix Beeching",
    email: "fbeeching1w@irs.gov",
    username: "fbeeching1w",
  },
  {
    id: 70,
    name: "Winifield Harvett",
    email: "wharvett1x@spiegel.de",
    username: "wharvett1x",
  },
  {
    id: 71,
    name: "Justinn Andrysiak",
    email: "jandrysiak1y@printfriendly.com",
    username: "jandrysiak1y",
  },
  {
    id: 72,
    name: "Rossie Larrosa",
    email: "rlarrosa1z@slideshare.net",
    username: "rlarrosa1z",
  },
  {
    id: 73,
    name: "Hatti Crowcum",
    email: "hcrowcum20@devhub.com",
    username: "hcrowcum20",
  },
  {
    id: 74,
    name: "Judd Josovich",
    email: "jjosovich21@accuweather.com",
    username: "jjosovich21",
  },
  {
    id: 75,
    name: "Herminia Dumphrey",
    email: "hdumphrey22@webs.com",
    username: "hdumphrey22",
  },
  {
    id: 76,
    name: "Vallie Bolle",
    email: "vbolle23@vkontakte.ru",
    username: "vbolle23",
  },
  {
    id: 77,
    name: "Jayson Forsdicke",
    email: "jforsdicke24@usda.gov",
    username: "jforsdicke24",
  },
  {
    id: 78,
    name: "Karylin Laurence",
    email: "klaurence25@sogou.com",
    username: "klaurence25",
  },
  {
    id: 79,
    name: "Tawnya Abthorpe",
    email: "tabthorpe26@pagesperso-orange.fr",
    username: "tabthorpe26",
  },
  {
    id: 80,
    name: "Roderic Moran",
    email: "rmoran27@intel.com",
    username: "rmoran27",
  },
  {
    id: 81,
    name: "Bartlet Elger",
    email: "belger28@canalblog.com",
    username: "belger28",
  },
  {
    id: 82,
    name: "Nicolas Hartzog",
    email: "nhartzog29@nps.gov",
    username: "nhartzog29",
  },
  {
    id: 83,
    name: "Georgiana Dadge",
    email: "gdadge2a@vinaora.com",
    username: "gdadge2a",
  },
  {
    id: 84,
    name: "Roseanna Housbie",
    email: "rhousbie2b@geocities.jp",
    username: "rhousbie2b",
  },
  {
    id: 85,
    name: "Donetta Bottelstone",
    email: "dbottelstone2c@vk.com",
    username: "dbottelstone2c",
  },
  {
    id: 86,
    name: "Marcos Grimwood",
    email: "mgrimwood2d@soup.io",
    username: "mgrimwood2d",
  },
  {
    id: 87,
    name: "Morna MacFarland",
    email: "mmacfarland2e@bbb.org",
    username: "mmacfarland2e",
  },
  {
    id: 88,
    name: "Addia Goodger",
    email: "agoodger2f@cocolog-nifty.com",
    username: "agoodger2f",
  },
  {
    id: 89,
    name: "Amanda Scamadine",
    email: "ascamadine2g@alexa.com",
    username: "ascamadine2g",
  },
  {
    id: 90,
    name: "Stella Tzuker",
    email: "stzuker2h@engadget.com",
    username: "stzuker2h",
  },
  {
    id: 91,
    name: "Wileen Unworth",
    email: "wunworth2i@so-net.ne.jp",
    username: "wunworth2i",
  },
  {
    id: 92,
    name: "Donnie Hamley",
    email: "dhamley2j@sakura.ne.jp",
    username: "dhamley2j",
  },
  {
    id: 93,
    name: "Georgy Kas",
    email: "gkas2k@quantcast.com",
    username: "gkas2k",
  },
  {
    id: 94,
    name: "Graham Aland",
    email: "galand2l@indiegogo.com",
    username: "galand2l",
  },
  {
    id: 95,
    name: "Jessie Wixey",
    email: "jwixey2m@ftc.gov",
    username: "jwixey2m",
  },
  {
    id: 96,
    name: "Olwen Sayer",
    email: "osayer2n@unicef.org",
    username: "osayer2n",
  },
  {
    id: 97,
    name: "Zorana Debrick",
    email: "zdebrick2o@google.com",
    username: "zdebrick2o",
  },
  {
    id: 98,
    name: "Modestia Kinsett",
    email: "mkinsett2p@123-reg.co.uk",
    username: "mkinsett2p",
  },
  {
    id: 99,
    name: "Rochella Honisch",
    email: "rhonisch2q@wikispaces.com",
    username: "rhonisch2q",
  },
  {
    id: 100,
    name: "Augustus Dawidowicz",
    email: "adawidowicz2r@bravesites.com",
    username: "adawidowicz2r",
  },
];
